name: Purge caches
on:
  push:
jobs:
  PurgeCaches:
    name: Purge Caches
    runs-on: ubuntu-latest
    steps:
      - name: Purge Cloudflare Cache
        shell: bash
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.JMONKEYENGINE_ORG_CLOUDFLARE_ZONE }}/purge_cache" \
          -H "Authorization: Bearer ${{ secrets.JMONKEYENGINE_ORG_CLOUDFLARE_API_KEY }}" \
          -H "Content-Type: application/json"  --data '{"purge_everything":true}' 
